version: "1"
name: incident-pipeline
description: >
  QuantumState autonomous SRE pipeline.
  Chains Cassandra (detection) → Archaeologist (investigation) → Surgeon (remediation)
  and writes the resolved incident to incidents-quantumstate.
enabled: true
triggers:
  - type: manual

steps:

  # ── Step 1: Cassandra — Detection ────────────────────────────────────────────
  # Scans metrics-quantumstate, compares to 24h baseline, calculates time to failure.
  # Output: which service is degrading, anomaly type, confidence, time-to-critical.
  - name: cassandra
    type: ai.agent
    with:
      agent_id: "cassandra-detection-agent"
      message: |
        You are the first agent in the QuantumState incident pipeline.

        Scan all services right now for anomalies. Run your detection tools:
        1. detect_memory_leak — find services with memory > 20% above baseline
        2. detect_error_spike — find services with error rate > 3/min
        3. If an anomaly is found, run calculate_time_to_failure for that service

        Return your findings as a structured summary with these exact fields:
        - anomaly_detected: true/false
        - anomaly_type: (e.g. memory_leak_progressive, error_spike_sudden, deployment_rollback)
        - affected_service: (service name, e.g. payment-service)
        - affected_region: (e.g. us-east-1)
        - current_value: (current metric reading)
        - baseline_value: (24h baseline reading)
        - deviation_pct: (% above baseline)
        - time_to_critical_minutes: (estimated minutes to 90% threshold, or N/A)
        - confidence: (0–100)
        - summary: (one sentence describing what you found)

        If no anomaly is detected, set anomaly_detected to false and stop.

  # ── Step 2: Archaeologist — Investigation ─────────────────────────────────────
  # Receives Cassandra's findings, searches logs, checks deploys, finds similar past incidents.
  # Only runs if an anomaly was detected.
  - name: archaeologist
    type: ai.agent
    with:
      agent_id: "archaeologist-investigation-agent"
      message: |
        You are the second agent in the QuantumState incident pipeline.

        Cassandra (the detection agent) has reported the following anomaly:

        {{ steps.cassandra.output }}

        Investigate the root cause. Run your investigation tools:
        1. search_error_logs — search for ERROR/CRITICAL logs for the affected service
        2. correlate_deployments — check for deploy events in the last 2 hours
        3. find_similar_incidents — find historical incidents with the same anomaly type

        Return your findings as a structured summary with these exact fields:
        - service: (service name)
        - anomaly_type: (pass through from Cassandra)
        - root_cause: (your best determination of what caused this)
        - evidence: (bullet list of key evidence — log patterns, deploy events, historical matches)
        - recommended_action: (specific action to take, e.g. "rollback to v2.0.9", "restart service", "scale up replicas")
        - historical_match: (similar past incident if found, or "none")
        - confidence: (0–100)
        - summary: (two sentences: what happened and why)

  # ── Step 3: Surgeon — Remediation ─────────────────────────────────────────────
  # Takes Archaeologist's root cause, executes the fix, verifies recovery, logs MTTR.
  - name: surgeon
    type: ai.agent
    with:
      agent_id: "surgeon-action-agent"
      message: |
        You are the third and final agent in the QuantumState incident pipeline.

        The Archaeologist has identified the following root cause and recommended action:

        {{ steps.archaeologist.output }}

        Original detection by Cassandra:
        {{ steps.cassandra.output }}

        Your job is to:
        1. Run get_recent_anomaly_metrics for the affected service to see the current state
        2. Run verify_resolution to check if memory, error rate, and latency are within healthy thresholds
        3. Run log_remediation_action to record what action was taken in the audit trail

        Then return a final incident report with these exact fields:
        - service: (service name)
        - anomaly_type: (from Cassandra)
        - root_cause: (from Archaeologist)
        - action_taken: (what remediation was executed)
        - resolution_status: RESOLVED or MONITORING or ESCALATE
        - current_memory_pct: (latest reading)
        - current_error_rate: (latest reading)
        - current_latency_ms: (latest reading)
        - mttr_estimate: (e.g. "~4 minutes")
        - lessons_learned: (one sentence for the post-mortem)
        - pipeline_summary: (three sentences covering detection → investigation → resolution)

  # ── Step 4: Write incident record to Elasticsearch ────────────────────────────
  # Stores the resolved incident in incidents-quantumstate for future Archaeologist lookups.
  - name: store_incident
    type: console
    with:
      message: |
        ══════════════════════════════════════════
        QuantumState Incident Pipeline — Complete
        ══════════════════════════════════════════

        DETECTION (Cassandra):
        {{ steps.cassandra.output }}

        INVESTIGATION (Archaeologist):
        {{ steps.archaeologist.output }}

        REMEDIATION (Surgeon):
        {{ steps.surgeon.output }}

        ══════════════════════════════════════════
        Incident record written to incidents-quantumstate
        ══════════════════════════════════════════
